### PR TITLE
Add network connection type option

### PR DESCRIPTION
**Pull request by zarenner**
#31 (#30) made it possible to start on Big Sur, but for some users the default 'nat' connection type may no longer work on Big Sur's internet sharing for those running DNS proxies due to https://communities.vmware.com/t5/VMware-Fusion-Discussions/DNS-Forwarder-Does-Not-Seem-to-Exist-in-VMware-Fusion-12-on-Big/td-p/2808576

> Well here's the problem!  Before Big Sur, VMware Fusion did its own DNS stuff, so it was unaffected by a service already bound to port 53 on the host.  But starting with Big Sur, VMware leverages os-level DNS dispatching.  The problem here is that the OS-level mDNSResponder handling of DNS requests appears to want to bind to every address.  And if something has already bound port 53, even just for the loopback address, this greedy attempt to bind port 53 everywhere results in port 53 being bound nowhere.  So as described above, any NAT-enabled VM in such a situation will have nothing to answer its DNS requests.

> If it's possible, a VMware-level fix would be to cause mDNSResponder to bind port 53 only on the network interfaces that VMware has configured / is using. That way, VMware Fusion should be guaranteed to not conflict with any network configuration that the machine operator has configured.

Since the NAT-based networking is therefore currently unusable in some cases, this PR makes it possible to use `bridged` networking instead until VMWare fixes the issue.

### CODE REVIEW

**Comment by zarenner** [comment]
FYI I intend to open a PR consuming this in minikube as soon as this is checked in and released.

**Comment by mikeroySoft** [comment]
I've got it building (had to update to go mods since the original repo hasn't done so yet)...
I'm not sure how to test tho... 
Would I do something like `docker-machine create --driver=vmware --engine-env VMWARE_NETWORK_TYPE=bridged` ?

**Comment by zarenner** [comment]
`docker-machine create --driver=vmware --vmware-network-type=bridged test` should work!

**Comment by mikeroySoft** [comment]
Ah, thanks!
I see what I did... I ran that command the first time, but had the order of flags out of whack...

```console
> docker-machine create --driver=vmware default --vmware-network-type=bridged
Invalid command line. Found extra arguments [--vmware-network-type=bridged]
```
derp... 

Ran it again with the name of the machine at the tail of the command, and it's booting up with an IP that I would expect =)

So great, we're good... I want to merge this, but I feel like we should get go mod support in there first... so let me work on that (there's a PR collecting dust on it) and then pull this one in at the same time.

**Comment by zarenner** [comment]
Thanks! I'll keep an eye out for whenever you decide to and figure out how to create a release 🙂

**Comment by mikeroySoft** [comment]
Release v0.1.3, which includes this change, has been published! 
It also the homebrew-tap formula, so you can just do a ` brew upgrade docker-machine-driver-vmware` =)

**Pull request merged**
